# Generated by Django 3.1.11 on 2021-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
