# Generated by Django 3.1.11 on 2021-05-30 03:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cancelada', models.BooleanField(default=False)),
                ('fecha_cita', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='DetalleVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('talla', models.CharField(blank=True, max_length=256)),
                ('peso', models.FloatField(blank=True)),
                ('cirugia', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(blank=True)),
                ('pulso', models.PositiveSmallIntegerField(default=0)),
                ('diagnostico', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('examen', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('receta_medica', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('img', models.ImageField(blank=True, null=True, upload_to='producto/img', verbose_name='imagen')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marca/img', verbose_name='imagen')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('edad', models.CharField(blank=True, max_length=256)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('especie', models.CharField(blank=True, max_length=256)),
                ('raza', models.CharField(blank=True, max_length=256)),
                ('alergias', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('color', models.CharField(blank=True, max_length=256)),
                ('procedencia', models.CharField(blank=True, max_length=256)),
                ('sexo', models.CharField(blank=True, choices=[('MACHO', 'MACHO'), ('HEMBRA', 'HEMBRA')], max_length=8, null=True)),
                ('estado_reproductivo', models.CharField(blank=True, max_length=256)),
                ('dni', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^\\d{8,8}$')])),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('enfermedad', models.CharField(max_length=256)),
                ('alergias', ckeditor.fields.RichTextField(blank=True, help_text='Puedes colocar videos, imágenes y texto', null=True)),
                ('raza', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('precio', models.FloatField(default=0.0)),
                ('stock', models.SmallIntegerField(default=0)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='producto/img', verbose_name='imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.marcaproducto')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
    ]
