# Generated by Django 3.1.11 on 2021-06-06 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('motivo', models.TextField(max_length=2048)),
                ('fecha_cita', models.DateTimeField()),
                ('cancelada', models.BooleanField(default=False)),
                ('atendida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': '02. Citas',
                'ordering': ['fecha_cita', 'created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especie/img')),
                ('tipo', models.CharField(choices=[('FELINO', 'FELINO'), ('CANINO', 'CANINO'), ('AVE', 'AVE'), ('ACUATICO', 'ACUATICO'), ('ROEDOR', 'ROEDOR'), ('GANADO', 'GANADO')], max_length=16)),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.TextField(blank=True, max_length=2048, null=True)),
                ('talla', models.CharField(blank=True, max_length=256)),
                ('peso', models.FloatField(blank=True, default=0.0, null=True)),
                ('tarea', models.CharField(choices=[('CONSULTA', 'CONSULTA'), ('CITA', 'CITA'), ('CIRUGIA', 'CIRUGIA'), ('VACUNA', 'VACUNA'), ('EXAMEN', 'EXAMEN')], max_length=16)),
                ('internado', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(blank=True, default=0.0, null=True)),
                ('pulso', models.PositiveSmallIntegerField(default=0)),
                ('diagnostico', models.TextField(blank=True, max_length=2048, null=True)),
                ('examen', models.TextField(blank=True, max_length=2048, null=True)),
                ('receta_medica', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': '04. Historiales',
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/img')),
            ],
            options={
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marca/img')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('edad', models.CharField(blank=True, max_length=256)),
                ('raza', models.CharField(blank=True, max_length=256)),
                ('color', models.CharField(blank=True, max_length=256)),
                ('alergias', models.TextField(blank=True, max_length=2048, null=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=8, null=True)),
                ('esterilizado', models.BooleanField(default=False, verbose_name='esterilizado y/o castrado')),
                ('entero', models.BooleanField(default=False)),
                ('gestacion', models.BooleanField(default=False)),
                ('lactancia', models.BooleanField(default=False)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^\\d{8,8}$')], verbose_name='DNI o RUM')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': '01. Mascotas',
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=256)),
                ('precio', models.FloatField(default=0.0)),
                ('stock', models.SmallIntegerField(default=0)),
                ('imagen_principal', models.ImageField(null=True, upload_to='producto/img')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.marcaproducto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': '03. Productos',
                'ordering': ['created', 'modified'],
            },
        ),
    ]
