# Generated by Django 3.1.11 on 2021-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20210602_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='cirugia',
            new_name='internado',
        ),
        migrations.AddField(
            model_name='historial',
            name='tarea',
            field=models.CharField(blank=True, choices=[('CONSULTA', 'CONSULTA'), ('CITA', 'CITA'), ('CIRUGIA', 'CIRUGIA'), ('VACUNA', 'VACUNA')], max_length=16),
        ),
    ]
