# Generated by Django 3.1.11 on 2021-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20210529_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='raza',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
