# Generated by Django 3.1.11 on 2021-06-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20210602_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='img',
            new_name='imagen',
        ),
    ]
