# Generated by Django 3.1.11 on 2021-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20210529_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
    ]
