# Generated by Django 3.1.11 on 2021-05-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_cita_atendida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'cita', 'verbose_name_plural': '02. Citas'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'historial', 'verbose_name_plural': '04. Historiales'},
        ),
        migrations.AlterModelOptions(
            name='marcaproducto',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'mascota', 'verbose_name_plural': '01. Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'producto', 'verbose_name_plural': '03. Productos'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
    ]
