# Generated by Django 3.1.11 on 2021-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_auto_20210602_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(null=True, upload_to='producto/img', verbose_name='imagen'),
        ),
    ]
