# Generated by Django 3.1.11 on 2021-06-05 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_auto_20210602_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especie/img')),
                ('tipo', models.CharField(choices=[('FELINO', 'FELINO'), ('CANINO', 'CANINO'), ('AVE', 'AVE'), ('ACUATICO', 'ACUATICO'), ('ROEDOR', 'ROEDOR'), ('GANADO', 'GANADO')], max_length=16)),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': '01. Especies',
                'ordering': ['created', 'modified'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'get_latest_by': 'fecha_cita', 'ordering': ['fecha_cita', 'created', 'modified'], 'verbose_name': 'cita', 'verbose_name_plural': '02. Citas'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified'], 'verbose_name': 'historial', 'verbose_name_plural': '04. Historiales'},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
        migrations.AlterModelOptions(
            name='marcaproducto',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified'], 'verbose_name': 'marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'get_latest_by': '-created', 'ordering': ['-created', '-modified'], 'verbose_name': 'mascota', 'verbose_name_plural': '01. Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified'], 'verbose_name': 'producto', 'verbose_name_plural': '03. Productos'},
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='estado_reproductivo',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='procedencia',
        ),
        migrations.AddField(
            model_name='mascota',
            name='entero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='esterilizado y/o castrado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='gestacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='lactancia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tarea',
            field=models.CharField(blank=True, choices=[('CONSULTA', 'CONSULTA'), ('CITA', 'CITA'), ('CIRUGIA', 'CIRUGIA'), ('VACUNA', 'VACUNA'), ('EXAMEN', 'EXAMEN')], max_length=16),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/img'),
        ),
        migrations.AlterField(
            model_name='marcaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marca/img'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='alergias',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^\\d{8,8}$')], verbose_name='DNI o RUM'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(null=True, upload_to='producto/img'),
        ),
        migrations.DeleteModel(
            name='DetalleVacuna',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.especie'),
        ),
    ]
