# Generated by Django 3.1.11 on 2021-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_auto_20210605_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified'], 'verbose_name': 'especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
