name: deploy to aws
on: 
  create:
    branches:
        - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: connect ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/ubuntu/veterinaria-back/
          git pull
          python3 manage.py collectstatic --noinput
          python3 manage.py migrate --noinput
          sudo systemctl restart gunicorn nginx
        host: api.rrqq.me
        user: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        
